export default {
    rewardBanana: {
      fakingRequest: false,
      angle: 90,
      decay: 0.91,
      spread: 100,
      startVelocity: 20,
      elementCount: 15,
      elementSize: 20,
      lifetime: 200,
      zIndex: 10,
      springAnimation: true,
      rewardPunish: 'reward',
      type: 'emoji',
      emoji: ['🍌', '🙈', '🍌', '🙉', '🍌', '🙊'],
    },
    removed: {
      fakingRequest: false,
      angle: 90,
      decay: 0.91,
      spread: 100,
      startVelocity: 20,
      elementCount: 15,
      elementSize: 20,
      lifetime: 200,
      zIndex: 10,
      springAnimation: true,
      rewardPunish: 'reward',
      type: 'emoji',
      emoji: ['💰', '🤑', '💰', '🙈'],
    },
    error: {
      fakingRequest: false,
      angle: 90,
      decay: 0.91,
      spread: 100,
      startVelocity: 20,
      elementCount: 15,
      elementSize: 20,
      lifetime: 200,
      zIndex: 10,
      springAnimation: true,
      rewardPunish: 'reward',
      type: 'emoji',
      emoji: ['😡', '😤', '😰', '🙈'],
    },
  }
  